### ISSUE TITLE
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.

### ISSUE THREAD

**Issue by TrudAX** [denissukhotin/MSSQLPlanToSpExecuteSql#1]
Doesn't work for the attached plan

************** Exception Text **************
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at MSSQLPlanToSpExecuteSql.StatementExtractorPre2016SP1.ExtractParmsData(XmlNode parameterListNode)
[StackTrace.txt](https://github.com/denissukhotin/MSSQLPlanToSpExecuteSql/files/3925319/StackTrace.txt)
   at MSSQLPlanToSpExecuteSql.StatementExtractor.ConvertStatement(XmlNode node)
   at MSSQLPlanToSpExecuteSql.StatementExtractor.Convert()

**Comment by denissukhotin** [comment]
Fixed
